### ISSUE TITLE
Your QuickCheck Talk Was Fantastic

### ISSUE THREAD

**Issue by jasonzoladz** [frasertweedale/talks#1]
Thanks for making it available on YouTube.  Well done.

**Comment by frasertweedale** [comment]
No problem; which variant did you watch?  I have done it at a couple of conferences.

**Comment by jasonzoladz** [comment]
I saw this one:
https://www.youtube.com/watch?v=TSDTDqoH_vM&list=WL&index=136

**Comment by frasertweedale** [comment]
Cool, thanks for clarifying, and thanks for the feedback.  Closing this issue now :)
